# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170221_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='countrty',
            new_name='country',
        ),
    ]
