# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-26 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_emailcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='email verification status'),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_verified',
            field=models.BooleanField(default=False, verbose_name='phone number verification status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, choices=[('P', 'Producer'), ('D', 'Director'), ('A', 'Actor'), ('C', 'Choreographer'), ('S', 'Stunt Master'), ('R', 'Reviewer')], default='', max_length=1),
        ),
    ]
