# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie',
            field=models.FileField(blank=True, max_length=700, null=True, upload_to='movies/'),
        ),
    ]
