# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-26 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170221_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(blank=True, choices=[('D', 'Drama'), ('A', 'Action'), ('T', 'Thriller'), ('F', 'Fantacy'), ('C', 'Animation')], max_length=1, null=True),
        ),
    ]
