# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 05:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170226_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='cast',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cast',
            name='image',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to='cast/image/'),
        ),
        migrations.AddField(
            model_name='cast',
            name='phone_number',
            field=models.CharField(default='', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. Up to 12 digits allowed.", regex='[0-9]{10,12}')], verbose_name='phone_number'),
        ),
    ]
