LOGIN_ERROR = "Incorrect password."
SIGNUP_ERROR = "Failed to register user."
PROFILE_GET_ERROR = "Error in getting the profile."
NON_EXISTENT_USER_ERROR = "User does not exist."
UNABLE_TO_LOGIN = "Unable to login."
NON_ACTIVE_USER_ERROR = "User is not active."

LOGIN_ERROR_0 = "user serializer errors."
LOGIN_ERROR_1 = "user with the given email or phone does not exist."
LOGIN_ERROR_2 = "both email and phone not verified hence not able to login."
LOGIN_ERROR_3 = "phone_number is not verified."
LOGIN_ERROR_4 = "email is not verified."
LOGIN_ERROR_5 = "incorrect password entered."
LOGIN_ERROR_6 = "non-active user."